name: Build

on:
  push:
    branches: master

jobs:
    build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Docker Hub Description
        uses: dbsqp/homekit-influxdbv2@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dbsqp/homekit-influxdbv2@latest
          short-description: ${{ github.event.repository.description }}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag dbsqp/homekit-influxdbv2:latest \
            --platform linux/amd64,linux/arm64 .

